# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BWiOSCommon' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BWiOSCommon

  pod 'Masonry'
  pod 'MBProgressHUD', '~> 1.0.0'

  target 'BWiOSCommonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BWiOSCommonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
